### ISSUE TITLE
Could not locate a deployable apk

### ISSUE THREAD

**Issue by cloudlene** [hamburml/ionic3-vs2017-blank-template#1]
Cloned & built the template with VS.Net 2017 (15.8.0) (and 2017 15.8.0 Preview 5.0).
The issue still exists.  I do see the "copyapk" in -vs-binding "AfterBuild" in package.json.  Not sure what it links to.  I'm using Global Cordova tools (8.0.0).  Build succeeds without warnings.
 
Built the following apk(s):
	C:\C#\ion3\ionic3-vs2017-blank-template\ion3\platforms\android\app\build\outputs\apk\debug\app-debug.apk
No scripts found for hook "after_build".
No scripts found for hook "after_compile".
------ Copying back to project: android
2>------ Deploy started: Project: ion3, Configuration: Debug Android ------
2>Could not locate a deployable apk. You may need to build your project.
2>Deployment failed.
========== Build: 1 succeeded, 0 failed, 0 up-to-date, 0 skipped ==========
========== Deploy: 0 succeeded, 1 failed, 0 skipped ==========

**Comment by cloudlene** [comment]
I have the fix for this issue.  But not able to submit it.
In config.xml, add a `<hook>` tag under:
```
<platform name="android">
         ......
        <hook src="copyapk.bat" type="after_build" />
</platform>
```
At the project folder create a copyapk.bat with the below line:
`copy "%1\platforms\android\app\build\outputs\apk\debug\*.apk"  "%1\bin\android\debug"`

**Comment by hamburml** [comment]
The `No scripts found for hook "after_build".` mentions that the copyapk binding wasn't found. I will try it out with an updated vs version. Coworker used this without any effort so there shouldn't be any changes necessary.

**Comment by cloudlene** [comment]
I did see this in packages.json:
```
  "-vs-binding": {
    "BeforeBuild": [
      "ionic:build"
    ],
    "AfterBuild": [
      "copyapk"
    ]
  }
```
It does mention "copyapk".  Unfortunately, I'm new to Cordova and can't see where the file & binding info need to go.  I've forked the code & updated my changes with an alternate approach.  Take a look.  This works for now, though, I would love to use the .Net Post Build macro "$(configuration)" or similar to ensure correct target location based on build type (DEBUG or RELEASE).  Thanks for your help.

**Comment by hamburml** [comment]
`copyapk` simply refers to this npm script (https://github.com/hamburml/ionic3-vs2017-blank-template/blob/master/ion3/package.json#L13), which is run by visual studio because a `-vs-binding` exists. I don't know if `.Net Post Bild macro "$(configuration)"` but I hope so because it's also from MS.

Let me see if I find a better solution with an npm script which runs after a build and considers the build type to use the correct location for the copy-command.

**Comment by cloudlene** [comment]
Visual studio. Without those changes, it doesn’t deploy.

**Comment by cloudlene** [comment]
Visual studio 2017.

**Comment by hamburml** [comment]
Have you installed the 'Task Runner Explorer' in VS 2017 and can you see the copyapk script under custom? 
![grafik](https://user-images.githubusercontent.com/7239350/45089111-70cc6480-b10b-11e8-897c-a2c5b65ec9bd.png)

*edit*
The solution with adding it to the config.xml works. But this addition means that if the app is build directly with the ionic-cli this hook also runs. But this is only needed when working with Visual Studio. I would advice against this workaround and try to find the reason why the `-vs-binding` isn't used by your visual studio.

**Comment by marckassay** [comment]
In addition to installing 'Task Runner Explorer' with Visual Studio Installer, one also needs to install ['NPM Task Runner'](https://marketplace.visualstudio.com/items?itemName=MadsKristensen.NPMTaskRunner). Perhaps @thinkfarahead's environment is missing that.

**Comment by hamburml** [comment]
@marckassay I am not sure but I think the `Task Runner Explorer` is only available when `NPM Task Runner` is installed. I should have been more precise.

Thanks for the link, I will add it to the readme.

**Comment by hamburml** [comment]
Closed
